apiVersion: v1
kind: Secret
metadata:
  name: motopp-secrets
  namespace: prod
type: Opaque
data:
  # Base64 for 'root_password_123'
  mysql-password: cm9vdF9wYXNzd29yZF8xMjM=
  # Base64 for 'my_secret_key_123'
  secret-key: bXlfc2VjcmV0X2tleV8xMjM=